version: '3'

services:

  app:
    build:
      context: app
    container_name: app
    networks:
      - node-network
    entrypoint: wait-for db:3306 -t 40 -- docker-entrypoint.sh
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db
    command: node index.js

  db:
    image: mysql:5.7
    command: --innodb_use_native_aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=username
    networks:
      - node-network

  nginx:
    build:
      context: nginx
    container_name: nginx
    tty: true
    ports:
     - "8080:80"
    networks:
      - node-network
    depends_on:
      - app

networks:
  node-network:
    driver: bridge